# Generated by Django 5.0.6 on 2024-06-24 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_student",
            new_name="學生",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="is_teacher",
            new_name="軍人",
        ),
    ]
